version: "3"
services:
  mailsnag:
    image: ghcr.io/alekangelov/mailsnag:latest
    ports:
      # access the smtp server at localhost:2525
      - 2525:2525
      # access the web ui at http://localhost:3333
      - 3333:3333
    environment:
      - SMTP_HOST=0.0.0.0
      - SMTP_PORT=2525
      - SMTP_AUTH_REQUIRED=false
      - SMTP_USERNAME=email
      - SMTP_PASSWORD=password
      - SERVER_HOST=localhost
      - SERVER_PORT=3333
