dev:
	air run .

test.all:
	go test -v ./main_test.go

test.plain:
	go test -v ./main_test.go -run TestPlain

test.html:
	go test -v ./main_test.go -run TestHtml

test.attachment:
	go test -v ./main_test.go -run TestAttachment